version: "3.9"

services:
    node-app:
        build:
            context: .
        environment: 
            - DB_HOST=mysqldb
            - DB_USER=seminar_sgroup
            - DB_PASSWORD=root
            - DB_NAME=123123
        restart: always
        ports:
            - 3001:3000
        depends_on: 
            - mysqldb
        networks: 
            - backendnetwork
    mysqldb:
        image: mysql:8.0.25
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            - MYSQL_ROOT_PASSWORD=123123
        volumes: 
            - ./migrations/:/docker-entrypoint-initdb.d
            - ./storage:/var/lib/mysql
        networks: 
            - backendnetwork

networks: 
    backendnetwork:
        driver: bridge