version: "3.9"

services:
    myapp:
        build:
            context: .
            args: 
                - db_host=mysqldb
                - db_name=seminar_sgroup
                - db_user=root
                - db_password=123123
        restart: always
        ports:
            - 3001:3000
        depends_on: 
            - mysqldb
        networks: 
            - backendnetwork
    mysqldb:
        image: mysql:8.0.25
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            - MYSQL_ROOT_PASSWORD=123123
            #- MYSQL_DATABASE=seminar_sgroup
        volumes: 
            - ./migrations/:/docker-entrypoint-initdb.d
        networks: 
            - backendnetwork

networks: 
    backendnetwork:
        driver: bridge